[project]
name = "omi_dagster_workspace_local"
requires-python = ">=3.9,<3.13"
version = "0.1.0"
dependencies = [
    "dagster==1.11.2",
    "dagster-webserver",
    "dagster-dg-cli",
]

[tool.dg]
directory_type = "deployment"


